// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/ddx/v1/countries_enum.proto
// Protobuf Java Version: 4.28.2

package proto.ddx.v1;

public final class CountriesEnum {
  private CountriesEnum() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CountriesEnum.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Country - enumeration of supported countries.
   * </pre>
   *
   * Protobuf enum {@code proto.ddx.v1.Country}
   */
  public enum Country
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Not available
     * </pre>
     *
     * <code>COUNTRY_NOT_AVAILABLE = 0;</code>
     */
    COUNTRY_NOT_AVAILABLE(0),
    /**
     * <pre>
     * AFGHANISTAN
     * </pre>
     *
     * <code>COUNTRY_AFGHANISTAN = 1;</code>
     */
    COUNTRY_AFGHANISTAN(1),
    /**
     * <pre>
     * ALBANIA
     * </pre>
     *
     * <code>COUNTRY_ALBANIA = 2;</code>
     */
    COUNTRY_ALBANIA(2),
    /**
     * <pre>
     * ALGERIA
     * </pre>
     *
     * <code>COUNTRY_ALGERIA = 3;</code>
     */
    COUNTRY_ALGERIA(3),
    /**
     * <pre>
     * ANTIGUA AND BARBUDA
     * </pre>
     *
     * <code>COUNTRY_ANTIGUA_AND_BARBUDA = 4;</code>
     */
    COUNTRY_ANTIGUA_AND_BARBUDA(4),
    /**
     * <pre>
     * ARGENTINA
     * </pre>
     *
     * <code>COUNTRY_ARGENTINA = 5;</code>
     */
    COUNTRY_ARGENTINA(5),
    /**
     * <pre>
     * ARMENIA
     * </pre>
     *
     * <code>COUNTRY_ARMENIA = 6;</code>
     */
    COUNTRY_ARMENIA(6),
    /**
     * <pre>
     * AUSTRALIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRALIA = 7;</code>
     */
    COUNTRY_AUSTRALIA(7),
    /**
     * <pre>
     * AUSTRIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRIA = 8;</code>
     */
    COUNTRY_AUSTRIA(8),
    /**
     * <pre>
     * AZERBAIJAN
     * </pre>
     *
     * <code>COUNTRY_AZERBAIJAN = 9;</code>
     */
    COUNTRY_AZERBAIJAN(9),
    /**
     * <pre>
     * BAHAMAS
     * </pre>
     *
     * <code>COUNTRY_BAHAMAS = 10;</code>
     */
    COUNTRY_BAHAMAS(10),
    /**
     * <pre>
     * BAHRAIN
     * </pre>
     *
     * <code>COUNTRY_BAHRAIN = 11;</code>
     */
    COUNTRY_BAHRAIN(11),
    /**
     * <pre>
     * BANGLADESH
     * </pre>
     *
     * <code>COUNTRY_BANGLADESH = 12;</code>
     */
    COUNTRY_BANGLADESH(12),
    /**
     * <pre>
     * BARBADOS
     * </pre>
     *
     * <code>COUNTRY_BARBADOS = 13;</code>
     */
    COUNTRY_BARBADOS(13),
    /**
     * <pre>
     * BELARUS
     * </pre>
     *
     * <code>COUNTRY_BELARUS = 14;</code>
     */
    COUNTRY_BELARUS(14),
    /**
     * <pre>
     * BELGIUM
     * </pre>
     *
     * <code>COUNTRY_BELGIUM = 15;</code>
     */
    COUNTRY_BELGIUM(15),
    /**
     * <pre>
     * BERMUDA
     * </pre>
     *
     * <code>COUNTRY_BERMUDA = 16;</code>
     */
    COUNTRY_BERMUDA(16),
    /**
     * <pre>
     * BOLIVIA
     * </pre>
     *
     * <code>COUNTRY_BOLIVIA = 17;</code>
     */
    COUNTRY_BOLIVIA(17),
    /**
     * <pre>
     * BOSNIA AND HERZEGOVINA
     * </pre>
     *
     * <code>COUNTRY_BOSNIA_AND_HERZEGOVINA = 18;</code>
     */
    COUNTRY_BOSNIA_AND_HERZEGOVINA(18),
    /**
     * <pre>
     * BRAZIL
     * </pre>
     *
     * <code>COUNTRY_BRAZIL = 19;</code>
     */
    COUNTRY_BRAZIL(19),
    /**
     * <pre>
     * BRUNEI
     * </pre>
     *
     * <code>COUNTRY_BRUNEI = 20;</code>
     */
    COUNTRY_BRUNEI(20),
    /**
     * <pre>
     * BULGARIA
     * </pre>
     *
     * <code>COUNTRY_BULGARIA = 21;</code>
     */
    COUNTRY_BULGARIA(21),
    /**
     * <pre>
     * CAMBODIA
     * </pre>
     *
     * <code>COUNTRY_CAMBODIA = 22;</code>
     */
    COUNTRY_CAMBODIA(22),
    /**
     * <pre>
     * CAMEROON
     * </pre>
     *
     * <code>COUNTRY_CAMEROON = 23;</code>
     */
    COUNTRY_CAMEROON(23),
    /**
     * <pre>
     * CANADA
     * </pre>
     *
     * <code>COUNTRY_CANADA = 24;</code>
     */
    COUNTRY_CANADA(24),
    /**
     * <pre>
     * CAYMAN ISLANDS
     * </pre>
     *
     * <code>COUNTRY_CAYMAN_ISLANDS = 25;</code>
     */
    COUNTRY_CAYMAN_ISLANDS(25),
    /**
     * <pre>
     * CHILE
     * </pre>
     *
     * <code>COUNTRY_CHILE = 26;</code>
     */
    COUNTRY_CHILE(26),
    /**
     * <pre>
     * CHINA
     * </pre>
     *
     * <code>COUNTRY_CHINA = 27;</code>
     */
    COUNTRY_CHINA(27),
    /**
     * <pre>
     * COLOMBIA
     * </pre>
     *
     * <code>COUNTRY_COLOMBIA = 28;</code>
     */
    COUNTRY_COLOMBIA(28),
    /**
     * <pre>
     * COSTA RICA
     * </pre>
     *
     * <code>COUNTRY_COSTA_RICA = 29;</code>
     */
    COUNTRY_COSTA_RICA(29),
    /**
     * <pre>
     * CROATIA
     * </pre>
     *
     * <code>COUNTRY_CROATIA = 30;</code>
     */
    COUNTRY_CROATIA(30),
    /**
     * <pre>
     * CUBA
     * </pre>
     *
     * <code>COUNTRY_CUBA = 31;</code>
     */
    COUNTRY_CUBA(31),
    /**
     * <pre>
     * CYPRUS
     * </pre>
     *
     * <code>COUNTRY_CYPRUS = 32;</code>
     */
    COUNTRY_CYPRUS(32),
    /**
     * <pre>
     * CZECHIA
     * </pre>
     *
     * <code>COUNTRY_CZECHIA = 33;</code>
     */
    COUNTRY_CZECHIA(33),
    /**
     * <pre>
     * DEMOCRATIC REPUBLIC OF THE CONGO
     * </pre>
     *
     * <code>COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 34;</code>
     */
    COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO(34),
    /**
     * <pre>
     * DENMARK
     * </pre>
     *
     * <code>COUNTRY_DENMARK = 35;</code>
     */
    COUNTRY_DENMARK(35),
    /**
     * <pre>
     * DOMINICAN REPUBLIC
     * </pre>
     *
     * <code>COUNTRY_DOMINICAN_REPUBLIC = 36;</code>
     */
    COUNTRY_DOMINICAN_REPUBLIC(36),
    /**
     * <pre>
     * ECUADOR
     * </pre>
     *
     * <code>COUNTRY_ECUADOR = 37;</code>
     */
    COUNTRY_ECUADOR(37),
    /**
     * <pre>
     * EGYPT
     * </pre>
     *
     * <code>COUNTRY_EGYPT = 38;</code>
     */
    COUNTRY_EGYPT(38),
    /**
     * <pre>
     * EL SALVADOR
     * </pre>
     *
     * <code>COUNTRY_EL_SALVADOR = 39;</code>
     */
    COUNTRY_EL_SALVADOR(39),
    /**
     * <pre>
     * ESTONIA
     * </pre>
     *
     * <code>COUNTRY_ESTONIA = 40;</code>
     */
    COUNTRY_ESTONIA(40),
    /**
     * <pre>
     * FINLAND
     * </pre>
     *
     * <code>COUNTRY_FINLAND = 41;</code>
     */
    COUNTRY_FINLAND(41),
    /**
     * <pre>
     * FRANCE
     * </pre>
     *
     * <code>COUNTRY_FRANCE = 42;</code>
     */
    COUNTRY_FRANCE(42),
    /**
     * <pre>
     * GEORGIA
     * </pre>
     *
     * <code>COUNTRY_GEORGIA = 43;</code>
     */
    COUNTRY_GEORGIA(43),
    /**
     * <pre>
     * GERMANY
     * </pre>
     *
     * <code>COUNTRY_GERMANY = 44;</code>
     */
    COUNTRY_GERMANY(44),
    /**
     * <pre>
     * GHANA
     * </pre>
     *
     * <code>COUNTRY_GHANA = 45;</code>
     */
    COUNTRY_GHANA(45),
    /**
     * <pre>
     * GREECE
     * </pre>
     *
     * <code>COUNTRY_GREECE = 46;</code>
     */
    COUNTRY_GREECE(46),
    /**
     * <pre>
     * GUATEMALA
     * </pre>
     *
     * <code>COUNTRY_GUATEMALA = 47;</code>
     */
    COUNTRY_GUATEMALA(47),
    /**
     * <pre>
     * HAITI
     * </pre>
     *
     * <code>COUNTRY_HAITI = 48;</code>
     */
    COUNTRY_HAITI(48),
    /**
     * <pre>
     * HONDURAS
     * </pre>
     *
     * <code>COUNTRY_HONDURAS = 49;</code>
     */
    COUNTRY_HONDURAS(49),
    /**
     * <pre>
     * HONG KONG
     * </pre>
     *
     * <code>COUNTRY_HONG_KONG = 50;</code>
     */
    COUNTRY_HONG_KONG(50),
    /**
     * <pre>
     * HUNGARY
     * </pre>
     *
     * <code>COUNTRY_HUNGARY = 51;</code>
     */
    COUNTRY_HUNGARY(51),
    /**
     * <pre>
     * ICELAND
     * </pre>
     *
     * <code>COUNTRY_ICELAND = 52;</code>
     */
    COUNTRY_ICELAND(52),
    /**
     * <pre>
     * INDIA
     * </pre>
     *
     * <code>COUNTRY_INDIA = 53;</code>
     */
    COUNTRY_INDIA(53),
    /**
     * <pre>
     * INDONESIA
     * </pre>
     *
     * <code>COUNTRY_INDONESIA = 54;</code>
     */
    COUNTRY_INDONESIA(54),
    /**
     * <pre>
     * IRAN
     * </pre>
     *
     * <code>COUNTRY_IRAN = 55;</code>
     */
    COUNTRY_IRAN(55),
    /**
     * <pre>
     * IRAQ
     * </pre>
     *
     * <code>COUNTRY_IRAQ = 56;</code>
     */
    COUNTRY_IRAQ(56),
    /**
     * <pre>
     * IRELAND
     * </pre>
     *
     * <code>COUNTRY_IRELAND = 57;</code>
     */
    COUNTRY_IRELAND(57),
    /**
     * <pre>
     * ISRAEL
     * </pre>
     *
     * <code>COUNTRY_ISRAEL = 58;</code>
     */
    COUNTRY_ISRAEL(58),
    /**
     * <pre>
     * ITALY
     * </pre>
     *
     * <code>COUNTRY_ITALY = 59;</code>
     */
    COUNTRY_ITALY(59),
    /**
     * <pre>
     * IVORY COAST
     * </pre>
     *
     * <code>COUNTRY_IVORY_COAST = 60;</code>
     */
    COUNTRY_IVORY_COAST(60),
    /**
     * <pre>
     * JAMAICA
     * </pre>
     *
     * <code>COUNTRY_JAMAICA = 61;</code>
     */
    COUNTRY_JAMAICA(61),
    /**
     * <pre>
     * JAPAN
     * </pre>
     *
     * <code>COUNTRY_JAPAN = 62;</code>
     */
    COUNTRY_JAPAN(62),
    /**
     * <pre>
     * JORDAN
     * </pre>
     *
     * <code>COUNTRY_JORDAN = 63;</code>
     */
    COUNTRY_JORDAN(63),
    /**
     * <pre>
     * KAZAKHSTAN
     * </pre>
     *
     * <code>COUNTRY_KAZAKHSTAN = 64;</code>
     */
    COUNTRY_KAZAKHSTAN(64),
    /**
     * <pre>
     * KENYA
     * </pre>
     *
     * <code>COUNTRY_KENYA = 65;</code>
     */
    COUNTRY_KENYA(65),
    /**
     * <pre>
     * KOSOVO
     * </pre>
     *
     * <code>COUNTRY_KOSOVO = 66;</code>
     */
    COUNTRY_KOSOVO(66),
    /**
     * <pre>
     * KUWAIT
     * </pre>
     *
     * <code>COUNTRY_KUWAIT = 67;</code>
     */
    COUNTRY_KUWAIT(67),
    /**
     * <pre>
     * LATVIA
     * </pre>
     *
     * <code>COUNTRY_LATVIA = 68;</code>
     */
    COUNTRY_LATVIA(68),
    /**
     * <pre>
     * LIBYA
     * </pre>
     *
     * <code>COUNTRY_LIBYA = 69;</code>
     */
    COUNTRY_LIBYA(69),
    /**
     * <pre>
     * LIECHTENSTEIN
     * </pre>
     *
     * <code>COUNTRY_LIECHTENSTEIN = 70;</code>
     */
    COUNTRY_LIECHTENSTEIN(70),
    /**
     * <pre>
     * LITHUANIA
     * </pre>
     *
     * <code>COUNTRY_LITHUANIA = 71;</code>
     */
    COUNTRY_LITHUANIA(71),
    /**
     * <pre>
     * LUXEMBOURG
     * </pre>
     *
     * <code>COUNTRY_LUXEMBOURG = 72;</code>
     */
    COUNTRY_LUXEMBOURG(72),
    /**
     * <pre>
     * MALAYSIA
     * </pre>
     *
     * <code>COUNTRY_MALAYSIA = 73;</code>
     */
    COUNTRY_MALAYSIA(73),
    /**
     * <pre>
     * MALDIVES
     * </pre>
     *
     * <code>COUNTRY_MALDIVES = 74;</code>
     */
    COUNTRY_MALDIVES(74),
    /**
     * <pre>
     * MALTA
     * </pre>
     *
     * <code>COUNTRY_MALTA = 75;</code>
     */
    COUNTRY_MALTA(75),
    /**
     * <pre>
     * MAURITIUS
     * </pre>
     *
     * <code>COUNTRY_MAURITIUS = 76;</code>
     */
    COUNTRY_MAURITIUS(76),
    /**
     * <pre>
     * MEXICO
     * </pre>
     *
     * <code>COUNTRY_MEXICO = 77;</code>
     */
    COUNTRY_MEXICO(77),
    /**
     * <pre>
     * MOLDOVA
     * </pre>
     *
     * <code>COUNTRY_MOLDOVA = 78;</code>
     */
    COUNTRY_MOLDOVA(78),
    /**
     * <pre>
     * MONACO
     * </pre>
     *
     * <code>COUNTRY_MONACO = 79;</code>
     */
    COUNTRY_MONACO(79),
    /**
     * <pre>
     * MONTENEGRO
     * </pre>
     *
     * <code>COUNTRY_MONTENEGRO = 80;</code>
     */
    COUNTRY_MONTENEGRO(80),
    /**
     * <pre>
     * MOROCCO
     * </pre>
     *
     * <code>COUNTRY_MOROCCO = 81;</code>
     */
    COUNTRY_MOROCCO(81),
    /**
     * <pre>
     * NAMIBIA
     * </pre>
     *
     * <code>COUNTRY_NAMIBIA = 82;</code>
     */
    COUNTRY_NAMIBIA(82),
    /**
     * <pre>
     * NEPAL
     * </pre>
     *
     * <code>COUNTRY_NEPAL = 83;</code>
     */
    COUNTRY_NEPAL(83),
    /**
     * <pre>
     * NETHERLANDS
     * </pre>
     *
     * <code>COUNTRY_NETHERLANDS = 84;</code>
     */
    COUNTRY_NETHERLANDS(84),
    /**
     * <pre>
     * NEW ZEALAND
     * </pre>
     *
     * <code>COUNTRY_NEW_ZEALAND = 85;</code>
     */
    COUNTRY_NEW_ZEALAND(85),
    /**
     * <pre>
     * NICARAGUA
     * </pre>
     *
     * <code>COUNTRY_NICARAGUA = 86;</code>
     */
    COUNTRY_NICARAGUA(86),
    /**
     * <pre>
     * NIGERIA
     * </pre>
     *
     * <code>COUNTRY_NIGERIA = 87;</code>
     */
    COUNTRY_NIGERIA(87),
    /**
     * <pre>
     * NORTH MACEDONIA
     * </pre>
     *
     * <code>COUNTRY_NORTH_MACEDONIA = 88;</code>
     */
    COUNTRY_NORTH_MACEDONIA(88),
    /**
     * <pre>
     * NORWAY
     * </pre>
     *
     * <code>COUNTRY_NORWAY = 89;</code>
     */
    COUNTRY_NORWAY(89),
    /**
     * <pre>
     * OMAN
     * </pre>
     *
     * <code>COUNTRY_OMAN = 90;</code>
     */
    COUNTRY_OMAN(90),
    /**
     * <pre>
     * PAKISTAN
     * </pre>
     *
     * <code>COUNTRY_PAKISTAN = 91;</code>
     */
    COUNTRY_PAKISTAN(91),
    /**
     * <pre>
     * PALESTINE
     * </pre>
     *
     * <code>COUNTRY_PALESTINE = 92;</code>
     */
    COUNTRY_PALESTINE(92),
    /**
     * <pre>
     * PANAMA
     * </pre>
     *
     * <code>COUNTRY_PANAMA = 93;</code>
     */
    COUNTRY_PANAMA(93),
    /**
     * <pre>
     * PARAGUAY
     * </pre>
     *
     * <code>COUNTRY_PARAGUAY = 94;</code>
     */
    COUNTRY_PARAGUAY(94),
    /**
     * <pre>
     * PERU
     * </pre>
     *
     * <code>COUNTRY_PERU = 95;</code>
     */
    COUNTRY_PERU(95),
    /**
     * <pre>
     * PHILIPPINES
     * </pre>
     *
     * <code>COUNTRY_PHILIPPINES = 96;</code>
     */
    COUNTRY_PHILIPPINES(96),
    /**
     * <pre>
     * POLAND
     * </pre>
     *
     * <code>COUNTRY_POLAND = 97;</code>
     */
    COUNTRY_POLAND(97),
    /**
     * <pre>
     * PORTUGAL
     * </pre>
     *
     * <code>COUNTRY_PORTUGAL = 98;</code>
     */
    COUNTRY_PORTUGAL(98),
    /**
     * <pre>
     * PUERTO RICO
     * </pre>
     *
     * <code>COUNTRY_PUERTO_RICO = 99;</code>
     */
    COUNTRY_PUERTO_RICO(99),
    /**
     * <pre>
     * QATAR
     * </pre>
     *
     * <code>COUNTRY_QATAR = 100;</code>
     */
    COUNTRY_QATAR(100),
    /**
     * <pre>
     * ROMANIA
     * </pre>
     *
     * <code>COUNTRY_ROMANIA = 101;</code>
     */
    COUNTRY_ROMANIA(101),
    /**
     * <pre>
     * RUSSIA
     * </pre>
     *
     * <code>COUNTRY_RUSSIA = 102;</code>
     */
    COUNTRY_RUSSIA(102),
    /**
     * <pre>
     * SAINT KITTS AND NEVIS
     * </pre>
     *
     * <code>COUNTRY_SAINT_KITTS_AND_NEVIS = 103;</code>
     */
    COUNTRY_SAINT_KITTS_AND_NEVIS(103),
    /**
     * <pre>
     * SAINT LUCIA
     * </pre>
     *
     * <code>COUNTRY_SAINT_LUCIA = 104;</code>
     */
    COUNTRY_SAINT_LUCIA(104),
    /**
     * <pre>
     * SAUDI ARABIA
     * </pre>
     *
     * <code>COUNTRY_SAUDI_ARABIA = 105;</code>
     */
    COUNTRY_SAUDI_ARABIA(105),
    /**
     * <pre>
     * SERBIA
     * </pre>
     *
     * <code>COUNTRY_SERBIA = 106;</code>
     */
    COUNTRY_SERBIA(106),
    /**
     * <pre>
     * SINGAPORE
     * </pre>
     *
     * <code>COUNTRY_SINGAPORE = 107;</code>
     */
    COUNTRY_SINGAPORE(107),
    /**
     * <pre>
     * SLOVAKIA
     * </pre>
     *
     * <code>COUNTRY_SLOVAKIA = 108;</code>
     */
    COUNTRY_SLOVAKIA(108),
    /**
     * <pre>
     * SLOVENIA
     * </pre>
     *
     * <code>COUNTRY_SLOVENIA = 109;</code>
     */
    COUNTRY_SLOVENIA(109),
    /**
     * <pre>
     * SOUTH AFRICA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_AFRICA = 110;</code>
     */
    COUNTRY_SOUTH_AFRICA(110),
    /**
     * <pre>
     * SOUTH KOREA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_KOREA = 111;</code>
     */
    COUNTRY_SOUTH_KOREA(111),
    /**
     * <pre>
     * SPAIN
     * </pre>
     *
     * <code>COUNTRY_SPAIN = 112;</code>
     */
    COUNTRY_SPAIN(112),
    /**
     * <pre>
     * SRI LANKA
     * </pre>
     *
     * <code>COUNTRY_SRI_LANKA = 113;</code>
     */
    COUNTRY_SRI_LANKA(113),
    /**
     * <pre>
     * SUDAN
     * </pre>
     *
     * <code>COUNTRY_SUDAN = 114;</code>
     */
    COUNTRY_SUDAN(114),
    /**
     * <pre>
     * SWEDEN
     * </pre>
     *
     * <code>COUNTRY_SWEDEN = 115;</code>
     */
    COUNTRY_SWEDEN(115),
    /**
     * <pre>
     * SWITZERLAND
     * </pre>
     *
     * <code>COUNTRY_SWITZERLAND = 116;</code>
     */
    COUNTRY_SWITZERLAND(116),
    /**
     * <pre>
     * TAIWAN
     * </pre>
     *
     * <code>COUNTRY_TAIWAN = 117;</code>
     */
    COUNTRY_TAIWAN(117),
    /**
     * <pre>
     * TANZANIA
     * </pre>
     *
     * <code>COUNTRY_TANZANIA = 118;</code>
     */
    COUNTRY_TANZANIA(118),
    /**
     * <pre>
     * THAILAND
     * </pre>
     *
     * <code>COUNTRY_THAILAND = 119;</code>
     */
    COUNTRY_THAILAND(119),
    /**
     * <pre>
     * TRINIDAD AND TOBAGO
     * </pre>
     *
     * <code>COUNTRY_TRINIDAD_AND_TOBAGO = 120;</code>
     */
    COUNTRY_TRINIDAD_AND_TOBAGO(120),
    /**
     * <pre>
     * TUNISIA
     * </pre>
     *
     * <code>COUNTRY_TUNISIA = 121;</code>
     */
    COUNTRY_TUNISIA(121),
    /**
     * <pre>
     * TURKEY
     * </pre>
     *
     * <code>COUNTRY_TURKEY = 122;</code>
     */
    COUNTRY_TURKEY(122),
    /**
     * <pre>
     * UAE
     * </pre>
     *
     * <code>COUNTRY_UAE = 123;</code>
     */
    COUNTRY_UAE(123),
    /**
     * <pre>
     * UK
     * </pre>
     *
     * <code>COUNTRY_UK = 124;</code>
     */
    COUNTRY_UK(124),
    /**
     * <pre>
     * UKRAINE
     * </pre>
     *
     * <code>COUNTRY_UKRAINE = 125;</code>
     */
    COUNTRY_UKRAINE(125),
    /**
     * <pre>
     * URUGUAY
     * </pre>
     *
     * <code>COUNTRY_URUGUAY = 126;</code>
     */
    COUNTRY_URUGUAY(126),
    /**
     * <pre>
     * USA
     * </pre>
     *
     * <code>COUNTRY_USA = 127;</code>
     */
    COUNTRY_USA(127),
    /**
     * <pre>
     * UZBEKISTAN
     * </pre>
     *
     * <code>COUNTRY_UZBEKISTAN = 128;</code>
     */
    COUNTRY_UZBEKISTAN(128),
    /**
     * <pre>
     * VENEZUELA
     * </pre>
     *
     * <code>COUNTRY_VENEZUELA = 129;</code>
     */
    COUNTRY_VENEZUELA(129),
    /**
     * <pre>
     * VIETNAM
     * </pre>
     *
     * <code>COUNTRY_VIETNAM = 130;</code>
     */
    COUNTRY_VIETNAM(130),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Country.class.getName());
    }
    /**
     * <pre>
     * Not available
     * </pre>
     *
     * <code>COUNTRY_NOT_AVAILABLE = 0;</code>
     */
    public static final int COUNTRY_NOT_AVAILABLE_VALUE = 0;
    /**
     * <pre>
     * AFGHANISTAN
     * </pre>
     *
     * <code>COUNTRY_AFGHANISTAN = 1;</code>
     */
    public static final int COUNTRY_AFGHANISTAN_VALUE = 1;
    /**
     * <pre>
     * ALBANIA
     * </pre>
     *
     * <code>COUNTRY_ALBANIA = 2;</code>
     */
    public static final int COUNTRY_ALBANIA_VALUE = 2;
    /**
     * <pre>
     * ALGERIA
     * </pre>
     *
     * <code>COUNTRY_ALGERIA = 3;</code>
     */
    public static final int COUNTRY_ALGERIA_VALUE = 3;
    /**
     * <pre>
     * ANTIGUA AND BARBUDA
     * </pre>
     *
     * <code>COUNTRY_ANTIGUA_AND_BARBUDA = 4;</code>
     */
    public static final int COUNTRY_ANTIGUA_AND_BARBUDA_VALUE = 4;
    /**
     * <pre>
     * ARGENTINA
     * </pre>
     *
     * <code>COUNTRY_ARGENTINA = 5;</code>
     */
    public static final int COUNTRY_ARGENTINA_VALUE = 5;
    /**
     * <pre>
     * ARMENIA
     * </pre>
     *
     * <code>COUNTRY_ARMENIA = 6;</code>
     */
    public static final int COUNTRY_ARMENIA_VALUE = 6;
    /**
     * <pre>
     * AUSTRALIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRALIA = 7;</code>
     */
    public static final int COUNTRY_AUSTRALIA_VALUE = 7;
    /**
     * <pre>
     * AUSTRIA
     * </pre>
     *
     * <code>COUNTRY_AUSTRIA = 8;</code>
     */
    public static final int COUNTRY_AUSTRIA_VALUE = 8;
    /**
     * <pre>
     * AZERBAIJAN
     * </pre>
     *
     * <code>COUNTRY_AZERBAIJAN = 9;</code>
     */
    public static final int COUNTRY_AZERBAIJAN_VALUE = 9;
    /**
     * <pre>
     * BAHAMAS
     * </pre>
     *
     * <code>COUNTRY_BAHAMAS = 10;</code>
     */
    public static final int COUNTRY_BAHAMAS_VALUE = 10;
    /**
     * <pre>
     * BAHRAIN
     * </pre>
     *
     * <code>COUNTRY_BAHRAIN = 11;</code>
     */
    public static final int COUNTRY_BAHRAIN_VALUE = 11;
    /**
     * <pre>
     * BANGLADESH
     * </pre>
     *
     * <code>COUNTRY_BANGLADESH = 12;</code>
     */
    public static final int COUNTRY_BANGLADESH_VALUE = 12;
    /**
     * <pre>
     * BARBADOS
     * </pre>
     *
     * <code>COUNTRY_BARBADOS = 13;</code>
     */
    public static final int COUNTRY_BARBADOS_VALUE = 13;
    /**
     * <pre>
     * BELARUS
     * </pre>
     *
     * <code>COUNTRY_BELARUS = 14;</code>
     */
    public static final int COUNTRY_BELARUS_VALUE = 14;
    /**
     * <pre>
     * BELGIUM
     * </pre>
     *
     * <code>COUNTRY_BELGIUM = 15;</code>
     */
    public static final int COUNTRY_BELGIUM_VALUE = 15;
    /**
     * <pre>
     * BERMUDA
     * </pre>
     *
     * <code>COUNTRY_BERMUDA = 16;</code>
     */
    public static final int COUNTRY_BERMUDA_VALUE = 16;
    /**
     * <pre>
     * BOLIVIA
     * </pre>
     *
     * <code>COUNTRY_BOLIVIA = 17;</code>
     */
    public static final int COUNTRY_BOLIVIA_VALUE = 17;
    /**
     * <pre>
     * BOSNIA AND HERZEGOVINA
     * </pre>
     *
     * <code>COUNTRY_BOSNIA_AND_HERZEGOVINA = 18;</code>
     */
    public static final int COUNTRY_BOSNIA_AND_HERZEGOVINA_VALUE = 18;
    /**
     * <pre>
     * BRAZIL
     * </pre>
     *
     * <code>COUNTRY_BRAZIL = 19;</code>
     */
    public static final int COUNTRY_BRAZIL_VALUE = 19;
    /**
     * <pre>
     * BRUNEI
     * </pre>
     *
     * <code>COUNTRY_BRUNEI = 20;</code>
     */
    public static final int COUNTRY_BRUNEI_VALUE = 20;
    /**
     * <pre>
     * BULGARIA
     * </pre>
     *
     * <code>COUNTRY_BULGARIA = 21;</code>
     */
    public static final int COUNTRY_BULGARIA_VALUE = 21;
    /**
     * <pre>
     * CAMBODIA
     * </pre>
     *
     * <code>COUNTRY_CAMBODIA = 22;</code>
     */
    public static final int COUNTRY_CAMBODIA_VALUE = 22;
    /**
     * <pre>
     * CAMEROON
     * </pre>
     *
     * <code>COUNTRY_CAMEROON = 23;</code>
     */
    public static final int COUNTRY_CAMEROON_VALUE = 23;
    /**
     * <pre>
     * CANADA
     * </pre>
     *
     * <code>COUNTRY_CANADA = 24;</code>
     */
    public static final int COUNTRY_CANADA_VALUE = 24;
    /**
     * <pre>
     * CAYMAN ISLANDS
     * </pre>
     *
     * <code>COUNTRY_CAYMAN_ISLANDS = 25;</code>
     */
    public static final int COUNTRY_CAYMAN_ISLANDS_VALUE = 25;
    /**
     * <pre>
     * CHILE
     * </pre>
     *
     * <code>COUNTRY_CHILE = 26;</code>
     */
    public static final int COUNTRY_CHILE_VALUE = 26;
    /**
     * <pre>
     * CHINA
     * </pre>
     *
     * <code>COUNTRY_CHINA = 27;</code>
     */
    public static final int COUNTRY_CHINA_VALUE = 27;
    /**
     * <pre>
     * COLOMBIA
     * </pre>
     *
     * <code>COUNTRY_COLOMBIA = 28;</code>
     */
    public static final int COUNTRY_COLOMBIA_VALUE = 28;
    /**
     * <pre>
     * COSTA RICA
     * </pre>
     *
     * <code>COUNTRY_COSTA_RICA = 29;</code>
     */
    public static final int COUNTRY_COSTA_RICA_VALUE = 29;
    /**
     * <pre>
     * CROATIA
     * </pre>
     *
     * <code>COUNTRY_CROATIA = 30;</code>
     */
    public static final int COUNTRY_CROATIA_VALUE = 30;
    /**
     * <pre>
     * CUBA
     * </pre>
     *
     * <code>COUNTRY_CUBA = 31;</code>
     */
    public static final int COUNTRY_CUBA_VALUE = 31;
    /**
     * <pre>
     * CYPRUS
     * </pre>
     *
     * <code>COUNTRY_CYPRUS = 32;</code>
     */
    public static final int COUNTRY_CYPRUS_VALUE = 32;
    /**
     * <pre>
     * CZECHIA
     * </pre>
     *
     * <code>COUNTRY_CZECHIA = 33;</code>
     */
    public static final int COUNTRY_CZECHIA_VALUE = 33;
    /**
     * <pre>
     * DEMOCRATIC REPUBLIC OF THE CONGO
     * </pre>
     *
     * <code>COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 34;</code>
     */
    public static final int COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO_VALUE = 34;
    /**
     * <pre>
     * DENMARK
     * </pre>
     *
     * <code>COUNTRY_DENMARK = 35;</code>
     */
    public static final int COUNTRY_DENMARK_VALUE = 35;
    /**
     * <pre>
     * DOMINICAN REPUBLIC
     * </pre>
     *
     * <code>COUNTRY_DOMINICAN_REPUBLIC = 36;</code>
     */
    public static final int COUNTRY_DOMINICAN_REPUBLIC_VALUE = 36;
    /**
     * <pre>
     * ECUADOR
     * </pre>
     *
     * <code>COUNTRY_ECUADOR = 37;</code>
     */
    public static final int COUNTRY_ECUADOR_VALUE = 37;
    /**
     * <pre>
     * EGYPT
     * </pre>
     *
     * <code>COUNTRY_EGYPT = 38;</code>
     */
    public static final int COUNTRY_EGYPT_VALUE = 38;
    /**
     * <pre>
     * EL SALVADOR
     * </pre>
     *
     * <code>COUNTRY_EL_SALVADOR = 39;</code>
     */
    public static final int COUNTRY_EL_SALVADOR_VALUE = 39;
    /**
     * <pre>
     * ESTONIA
     * </pre>
     *
     * <code>COUNTRY_ESTONIA = 40;</code>
     */
    public static final int COUNTRY_ESTONIA_VALUE = 40;
    /**
     * <pre>
     * FINLAND
     * </pre>
     *
     * <code>COUNTRY_FINLAND = 41;</code>
     */
    public static final int COUNTRY_FINLAND_VALUE = 41;
    /**
     * <pre>
     * FRANCE
     * </pre>
     *
     * <code>COUNTRY_FRANCE = 42;</code>
     */
    public static final int COUNTRY_FRANCE_VALUE = 42;
    /**
     * <pre>
     * GEORGIA
     * </pre>
     *
     * <code>COUNTRY_GEORGIA = 43;</code>
     */
    public static final int COUNTRY_GEORGIA_VALUE = 43;
    /**
     * <pre>
     * GERMANY
     * </pre>
     *
     * <code>COUNTRY_GERMANY = 44;</code>
     */
    public static final int COUNTRY_GERMANY_VALUE = 44;
    /**
     * <pre>
     * GHANA
     * </pre>
     *
     * <code>COUNTRY_GHANA = 45;</code>
     */
    public static final int COUNTRY_GHANA_VALUE = 45;
    /**
     * <pre>
     * GREECE
     * </pre>
     *
     * <code>COUNTRY_GREECE = 46;</code>
     */
    public static final int COUNTRY_GREECE_VALUE = 46;
    /**
     * <pre>
     * GUATEMALA
     * </pre>
     *
     * <code>COUNTRY_GUATEMALA = 47;</code>
     */
    public static final int COUNTRY_GUATEMALA_VALUE = 47;
    /**
     * <pre>
     * HAITI
     * </pre>
     *
     * <code>COUNTRY_HAITI = 48;</code>
     */
    public static final int COUNTRY_HAITI_VALUE = 48;
    /**
     * <pre>
     * HONDURAS
     * </pre>
     *
     * <code>COUNTRY_HONDURAS = 49;</code>
     */
    public static final int COUNTRY_HONDURAS_VALUE = 49;
    /**
     * <pre>
     * HONG KONG
     * </pre>
     *
     * <code>COUNTRY_HONG_KONG = 50;</code>
     */
    public static final int COUNTRY_HONG_KONG_VALUE = 50;
    /**
     * <pre>
     * HUNGARY
     * </pre>
     *
     * <code>COUNTRY_HUNGARY = 51;</code>
     */
    public static final int COUNTRY_HUNGARY_VALUE = 51;
    /**
     * <pre>
     * ICELAND
     * </pre>
     *
     * <code>COUNTRY_ICELAND = 52;</code>
     */
    public static final int COUNTRY_ICELAND_VALUE = 52;
    /**
     * <pre>
     * INDIA
     * </pre>
     *
     * <code>COUNTRY_INDIA = 53;</code>
     */
    public static final int COUNTRY_INDIA_VALUE = 53;
    /**
     * <pre>
     * INDONESIA
     * </pre>
     *
     * <code>COUNTRY_INDONESIA = 54;</code>
     */
    public static final int COUNTRY_INDONESIA_VALUE = 54;
    /**
     * <pre>
     * IRAN
     * </pre>
     *
     * <code>COUNTRY_IRAN = 55;</code>
     */
    public static final int COUNTRY_IRAN_VALUE = 55;
    /**
     * <pre>
     * IRAQ
     * </pre>
     *
     * <code>COUNTRY_IRAQ = 56;</code>
     */
    public static final int COUNTRY_IRAQ_VALUE = 56;
    /**
     * <pre>
     * IRELAND
     * </pre>
     *
     * <code>COUNTRY_IRELAND = 57;</code>
     */
    public static final int COUNTRY_IRELAND_VALUE = 57;
    /**
     * <pre>
     * ISRAEL
     * </pre>
     *
     * <code>COUNTRY_ISRAEL = 58;</code>
     */
    public static final int COUNTRY_ISRAEL_VALUE = 58;
    /**
     * <pre>
     * ITALY
     * </pre>
     *
     * <code>COUNTRY_ITALY = 59;</code>
     */
    public static final int COUNTRY_ITALY_VALUE = 59;
    /**
     * <pre>
     * IVORY COAST
     * </pre>
     *
     * <code>COUNTRY_IVORY_COAST = 60;</code>
     */
    public static final int COUNTRY_IVORY_COAST_VALUE = 60;
    /**
     * <pre>
     * JAMAICA
     * </pre>
     *
     * <code>COUNTRY_JAMAICA = 61;</code>
     */
    public static final int COUNTRY_JAMAICA_VALUE = 61;
    /**
     * <pre>
     * JAPAN
     * </pre>
     *
     * <code>COUNTRY_JAPAN = 62;</code>
     */
    public static final int COUNTRY_JAPAN_VALUE = 62;
    /**
     * <pre>
     * JORDAN
     * </pre>
     *
     * <code>COUNTRY_JORDAN = 63;</code>
     */
    public static final int COUNTRY_JORDAN_VALUE = 63;
    /**
     * <pre>
     * KAZAKHSTAN
     * </pre>
     *
     * <code>COUNTRY_KAZAKHSTAN = 64;</code>
     */
    public static final int COUNTRY_KAZAKHSTAN_VALUE = 64;
    /**
     * <pre>
     * KENYA
     * </pre>
     *
     * <code>COUNTRY_KENYA = 65;</code>
     */
    public static final int COUNTRY_KENYA_VALUE = 65;
    /**
     * <pre>
     * KOSOVO
     * </pre>
     *
     * <code>COUNTRY_KOSOVO = 66;</code>
     */
    public static final int COUNTRY_KOSOVO_VALUE = 66;
    /**
     * <pre>
     * KUWAIT
     * </pre>
     *
     * <code>COUNTRY_KUWAIT = 67;</code>
     */
    public static final int COUNTRY_KUWAIT_VALUE = 67;
    /**
     * <pre>
     * LATVIA
     * </pre>
     *
     * <code>COUNTRY_LATVIA = 68;</code>
     */
    public static final int COUNTRY_LATVIA_VALUE = 68;
    /**
     * <pre>
     * LIBYA
     * </pre>
     *
     * <code>COUNTRY_LIBYA = 69;</code>
     */
    public static final int COUNTRY_LIBYA_VALUE = 69;
    /**
     * <pre>
     * LIECHTENSTEIN
     * </pre>
     *
     * <code>COUNTRY_LIECHTENSTEIN = 70;</code>
     */
    public static final int COUNTRY_LIECHTENSTEIN_VALUE = 70;
    /**
     * <pre>
     * LITHUANIA
     * </pre>
     *
     * <code>COUNTRY_LITHUANIA = 71;</code>
     */
    public static final int COUNTRY_LITHUANIA_VALUE = 71;
    /**
     * <pre>
     * LUXEMBOURG
     * </pre>
     *
     * <code>COUNTRY_LUXEMBOURG = 72;</code>
     */
    public static final int COUNTRY_LUXEMBOURG_VALUE = 72;
    /**
     * <pre>
     * MALAYSIA
     * </pre>
     *
     * <code>COUNTRY_MALAYSIA = 73;</code>
     */
    public static final int COUNTRY_MALAYSIA_VALUE = 73;
    /**
     * <pre>
     * MALDIVES
     * </pre>
     *
     * <code>COUNTRY_MALDIVES = 74;</code>
     */
    public static final int COUNTRY_MALDIVES_VALUE = 74;
    /**
     * <pre>
     * MALTA
     * </pre>
     *
     * <code>COUNTRY_MALTA = 75;</code>
     */
    public static final int COUNTRY_MALTA_VALUE = 75;
    /**
     * <pre>
     * MAURITIUS
     * </pre>
     *
     * <code>COUNTRY_MAURITIUS = 76;</code>
     */
    public static final int COUNTRY_MAURITIUS_VALUE = 76;
    /**
     * <pre>
     * MEXICO
     * </pre>
     *
     * <code>COUNTRY_MEXICO = 77;</code>
     */
    public static final int COUNTRY_MEXICO_VALUE = 77;
    /**
     * <pre>
     * MOLDOVA
     * </pre>
     *
     * <code>COUNTRY_MOLDOVA = 78;</code>
     */
    public static final int COUNTRY_MOLDOVA_VALUE = 78;
    /**
     * <pre>
     * MONACO
     * </pre>
     *
     * <code>COUNTRY_MONACO = 79;</code>
     */
    public static final int COUNTRY_MONACO_VALUE = 79;
    /**
     * <pre>
     * MONTENEGRO
     * </pre>
     *
     * <code>COUNTRY_MONTENEGRO = 80;</code>
     */
    public static final int COUNTRY_MONTENEGRO_VALUE = 80;
    /**
     * <pre>
     * MOROCCO
     * </pre>
     *
     * <code>COUNTRY_MOROCCO = 81;</code>
     */
    public static final int COUNTRY_MOROCCO_VALUE = 81;
    /**
     * <pre>
     * NAMIBIA
     * </pre>
     *
     * <code>COUNTRY_NAMIBIA = 82;</code>
     */
    public static final int COUNTRY_NAMIBIA_VALUE = 82;
    /**
     * <pre>
     * NEPAL
     * </pre>
     *
     * <code>COUNTRY_NEPAL = 83;</code>
     */
    public static final int COUNTRY_NEPAL_VALUE = 83;
    /**
     * <pre>
     * NETHERLANDS
     * </pre>
     *
     * <code>COUNTRY_NETHERLANDS = 84;</code>
     */
    public static final int COUNTRY_NETHERLANDS_VALUE = 84;
    /**
     * <pre>
     * NEW ZEALAND
     * </pre>
     *
     * <code>COUNTRY_NEW_ZEALAND = 85;</code>
     */
    public static final int COUNTRY_NEW_ZEALAND_VALUE = 85;
    /**
     * <pre>
     * NICARAGUA
     * </pre>
     *
     * <code>COUNTRY_NICARAGUA = 86;</code>
     */
    public static final int COUNTRY_NICARAGUA_VALUE = 86;
    /**
     * <pre>
     * NIGERIA
     * </pre>
     *
     * <code>COUNTRY_NIGERIA = 87;</code>
     */
    public static final int COUNTRY_NIGERIA_VALUE = 87;
    /**
     * <pre>
     * NORTH MACEDONIA
     * </pre>
     *
     * <code>COUNTRY_NORTH_MACEDONIA = 88;</code>
     */
    public static final int COUNTRY_NORTH_MACEDONIA_VALUE = 88;
    /**
     * <pre>
     * NORWAY
     * </pre>
     *
     * <code>COUNTRY_NORWAY = 89;</code>
     */
    public static final int COUNTRY_NORWAY_VALUE = 89;
    /**
     * <pre>
     * OMAN
     * </pre>
     *
     * <code>COUNTRY_OMAN = 90;</code>
     */
    public static final int COUNTRY_OMAN_VALUE = 90;
    /**
     * <pre>
     * PAKISTAN
     * </pre>
     *
     * <code>COUNTRY_PAKISTAN = 91;</code>
     */
    public static final int COUNTRY_PAKISTAN_VALUE = 91;
    /**
     * <pre>
     * PALESTINE
     * </pre>
     *
     * <code>COUNTRY_PALESTINE = 92;</code>
     */
    public static final int COUNTRY_PALESTINE_VALUE = 92;
    /**
     * <pre>
     * PANAMA
     * </pre>
     *
     * <code>COUNTRY_PANAMA = 93;</code>
     */
    public static final int COUNTRY_PANAMA_VALUE = 93;
    /**
     * <pre>
     * PARAGUAY
     * </pre>
     *
     * <code>COUNTRY_PARAGUAY = 94;</code>
     */
    public static final int COUNTRY_PARAGUAY_VALUE = 94;
    /**
     * <pre>
     * PERU
     * </pre>
     *
     * <code>COUNTRY_PERU = 95;</code>
     */
    public static final int COUNTRY_PERU_VALUE = 95;
    /**
     * <pre>
     * PHILIPPINES
     * </pre>
     *
     * <code>COUNTRY_PHILIPPINES = 96;</code>
     */
    public static final int COUNTRY_PHILIPPINES_VALUE = 96;
    /**
     * <pre>
     * POLAND
     * </pre>
     *
     * <code>COUNTRY_POLAND = 97;</code>
     */
    public static final int COUNTRY_POLAND_VALUE = 97;
    /**
     * <pre>
     * PORTUGAL
     * </pre>
     *
     * <code>COUNTRY_PORTUGAL = 98;</code>
     */
    public static final int COUNTRY_PORTUGAL_VALUE = 98;
    /**
     * <pre>
     * PUERTO RICO
     * </pre>
     *
     * <code>COUNTRY_PUERTO_RICO = 99;</code>
     */
    public static final int COUNTRY_PUERTO_RICO_VALUE = 99;
    /**
     * <pre>
     * QATAR
     * </pre>
     *
     * <code>COUNTRY_QATAR = 100;</code>
     */
    public static final int COUNTRY_QATAR_VALUE = 100;
    /**
     * <pre>
     * ROMANIA
     * </pre>
     *
     * <code>COUNTRY_ROMANIA = 101;</code>
     */
    public static final int COUNTRY_ROMANIA_VALUE = 101;
    /**
     * <pre>
     * RUSSIA
     * </pre>
     *
     * <code>COUNTRY_RUSSIA = 102;</code>
     */
    public static final int COUNTRY_RUSSIA_VALUE = 102;
    /**
     * <pre>
     * SAINT KITTS AND NEVIS
     * </pre>
     *
     * <code>COUNTRY_SAINT_KITTS_AND_NEVIS = 103;</code>
     */
    public static final int COUNTRY_SAINT_KITTS_AND_NEVIS_VALUE = 103;
    /**
     * <pre>
     * SAINT LUCIA
     * </pre>
     *
     * <code>COUNTRY_SAINT_LUCIA = 104;</code>
     */
    public static final int COUNTRY_SAINT_LUCIA_VALUE = 104;
    /**
     * <pre>
     * SAUDI ARABIA
     * </pre>
     *
     * <code>COUNTRY_SAUDI_ARABIA = 105;</code>
     */
    public static final int COUNTRY_SAUDI_ARABIA_VALUE = 105;
    /**
     * <pre>
     * SERBIA
     * </pre>
     *
     * <code>COUNTRY_SERBIA = 106;</code>
     */
    public static final int COUNTRY_SERBIA_VALUE = 106;
    /**
     * <pre>
     * SINGAPORE
     * </pre>
     *
     * <code>COUNTRY_SINGAPORE = 107;</code>
     */
    public static final int COUNTRY_SINGAPORE_VALUE = 107;
    /**
     * <pre>
     * SLOVAKIA
     * </pre>
     *
     * <code>COUNTRY_SLOVAKIA = 108;</code>
     */
    public static final int COUNTRY_SLOVAKIA_VALUE = 108;
    /**
     * <pre>
     * SLOVENIA
     * </pre>
     *
     * <code>COUNTRY_SLOVENIA = 109;</code>
     */
    public static final int COUNTRY_SLOVENIA_VALUE = 109;
    /**
     * <pre>
     * SOUTH AFRICA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_AFRICA = 110;</code>
     */
    public static final int COUNTRY_SOUTH_AFRICA_VALUE = 110;
    /**
     * <pre>
     * SOUTH KOREA
     * </pre>
     *
     * <code>COUNTRY_SOUTH_KOREA = 111;</code>
     */
    public static final int COUNTRY_SOUTH_KOREA_VALUE = 111;
    /**
     * <pre>
     * SPAIN
     * </pre>
     *
     * <code>COUNTRY_SPAIN = 112;</code>
     */
    public static final int COUNTRY_SPAIN_VALUE = 112;
    /**
     * <pre>
     * SRI LANKA
     * </pre>
     *
     * <code>COUNTRY_SRI_LANKA = 113;</code>
     */
    public static final int COUNTRY_SRI_LANKA_VALUE = 113;
    /**
     * <pre>
     * SUDAN
     * </pre>
     *
     * <code>COUNTRY_SUDAN = 114;</code>
     */
    public static final int COUNTRY_SUDAN_VALUE = 114;
    /**
     * <pre>
     * SWEDEN
     * </pre>
     *
     * <code>COUNTRY_SWEDEN = 115;</code>
     */
    public static final int COUNTRY_SWEDEN_VALUE = 115;
    /**
     * <pre>
     * SWITZERLAND
     * </pre>
     *
     * <code>COUNTRY_SWITZERLAND = 116;</code>
     */
    public static final int COUNTRY_SWITZERLAND_VALUE = 116;
    /**
     * <pre>
     * TAIWAN
     * </pre>
     *
     * <code>COUNTRY_TAIWAN = 117;</code>
     */
    public static final int COUNTRY_TAIWAN_VALUE = 117;
    /**
     * <pre>
     * TANZANIA
     * </pre>
     *
     * <code>COUNTRY_TANZANIA = 118;</code>
     */
    public static final int COUNTRY_TANZANIA_VALUE = 118;
    /**
     * <pre>
     * THAILAND
     * </pre>
     *
     * <code>COUNTRY_THAILAND = 119;</code>
     */
    public static final int COUNTRY_THAILAND_VALUE = 119;
    /**
     * <pre>
     * TRINIDAD AND TOBAGO
     * </pre>
     *
     * <code>COUNTRY_TRINIDAD_AND_TOBAGO = 120;</code>
     */
    public static final int COUNTRY_TRINIDAD_AND_TOBAGO_VALUE = 120;
    /**
     * <pre>
     * TUNISIA
     * </pre>
     *
     * <code>COUNTRY_TUNISIA = 121;</code>
     */
    public static final int COUNTRY_TUNISIA_VALUE = 121;
    /**
     * <pre>
     * TURKEY
     * </pre>
     *
     * <code>COUNTRY_TURKEY = 122;</code>
     */
    public static final int COUNTRY_TURKEY_VALUE = 122;
    /**
     * <pre>
     * UAE
     * </pre>
     *
     * <code>COUNTRY_UAE = 123;</code>
     */
    public static final int COUNTRY_UAE_VALUE = 123;
    /**
     * <pre>
     * UK
     * </pre>
     *
     * <code>COUNTRY_UK = 124;</code>
     */
    public static final int COUNTRY_UK_VALUE = 124;
    /**
     * <pre>
     * UKRAINE
     * </pre>
     *
     * <code>COUNTRY_UKRAINE = 125;</code>
     */
    public static final int COUNTRY_UKRAINE_VALUE = 125;
    /**
     * <pre>
     * URUGUAY
     * </pre>
     *
     * <code>COUNTRY_URUGUAY = 126;</code>
     */
    public static final int COUNTRY_URUGUAY_VALUE = 126;
    /**
     * <pre>
     * USA
     * </pre>
     *
     * <code>COUNTRY_USA = 127;</code>
     */
    public static final int COUNTRY_USA_VALUE = 127;
    /**
     * <pre>
     * UZBEKISTAN
     * </pre>
     *
     * <code>COUNTRY_UZBEKISTAN = 128;</code>
     */
    public static final int COUNTRY_UZBEKISTAN_VALUE = 128;
    /**
     * <pre>
     * VENEZUELA
     * </pre>
     *
     * <code>COUNTRY_VENEZUELA = 129;</code>
     */
    public static final int COUNTRY_VENEZUELA_VALUE = 129;
    /**
     * <pre>
     * VIETNAM
     * </pre>
     *
     * <code>COUNTRY_VIETNAM = 130;</code>
     */
    public static final int COUNTRY_VIETNAM_VALUE = 130;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Country valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Country forNumber(int value) {
      switch (value) {
        case 0: return COUNTRY_NOT_AVAILABLE;
        case 1: return COUNTRY_AFGHANISTAN;
        case 2: return COUNTRY_ALBANIA;
        case 3: return COUNTRY_ALGERIA;
        case 4: return COUNTRY_ANTIGUA_AND_BARBUDA;
        case 5: return COUNTRY_ARGENTINA;
        case 6: return COUNTRY_ARMENIA;
        case 7: return COUNTRY_AUSTRALIA;
        case 8: return COUNTRY_AUSTRIA;
        case 9: return COUNTRY_AZERBAIJAN;
        case 10: return COUNTRY_BAHAMAS;
        case 11: return COUNTRY_BAHRAIN;
        case 12: return COUNTRY_BANGLADESH;
        case 13: return COUNTRY_BARBADOS;
        case 14: return COUNTRY_BELARUS;
        case 15: return COUNTRY_BELGIUM;
        case 16: return COUNTRY_BERMUDA;
        case 17: return COUNTRY_BOLIVIA;
        case 18: return COUNTRY_BOSNIA_AND_HERZEGOVINA;
        case 19: return COUNTRY_BRAZIL;
        case 20: return COUNTRY_BRUNEI;
        case 21: return COUNTRY_BULGARIA;
        case 22: return COUNTRY_CAMBODIA;
        case 23: return COUNTRY_CAMEROON;
        case 24: return COUNTRY_CANADA;
        case 25: return COUNTRY_CAYMAN_ISLANDS;
        case 26: return COUNTRY_CHILE;
        case 27: return COUNTRY_CHINA;
        case 28: return COUNTRY_COLOMBIA;
        case 29: return COUNTRY_COSTA_RICA;
        case 30: return COUNTRY_CROATIA;
        case 31: return COUNTRY_CUBA;
        case 32: return COUNTRY_CYPRUS;
        case 33: return COUNTRY_CZECHIA;
        case 34: return COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO;
        case 35: return COUNTRY_DENMARK;
        case 36: return COUNTRY_DOMINICAN_REPUBLIC;
        case 37: return COUNTRY_ECUADOR;
        case 38: return COUNTRY_EGYPT;
        case 39: return COUNTRY_EL_SALVADOR;
        case 40: return COUNTRY_ESTONIA;
        case 41: return COUNTRY_FINLAND;
        case 42: return COUNTRY_FRANCE;
        case 43: return COUNTRY_GEORGIA;
        case 44: return COUNTRY_GERMANY;
        case 45: return COUNTRY_GHANA;
        case 46: return COUNTRY_GREECE;
        case 47: return COUNTRY_GUATEMALA;
        case 48: return COUNTRY_HAITI;
        case 49: return COUNTRY_HONDURAS;
        case 50: return COUNTRY_HONG_KONG;
        case 51: return COUNTRY_HUNGARY;
        case 52: return COUNTRY_ICELAND;
        case 53: return COUNTRY_INDIA;
        case 54: return COUNTRY_INDONESIA;
        case 55: return COUNTRY_IRAN;
        case 56: return COUNTRY_IRAQ;
        case 57: return COUNTRY_IRELAND;
        case 58: return COUNTRY_ISRAEL;
        case 59: return COUNTRY_ITALY;
        case 60: return COUNTRY_IVORY_COAST;
        case 61: return COUNTRY_JAMAICA;
        case 62: return COUNTRY_JAPAN;
        case 63: return COUNTRY_JORDAN;
        case 64: return COUNTRY_KAZAKHSTAN;
        case 65: return COUNTRY_KENYA;
        case 66: return COUNTRY_KOSOVO;
        case 67: return COUNTRY_KUWAIT;
        case 68: return COUNTRY_LATVIA;
        case 69: return COUNTRY_LIBYA;
        case 70: return COUNTRY_LIECHTENSTEIN;
        case 71: return COUNTRY_LITHUANIA;
        case 72: return COUNTRY_LUXEMBOURG;
        case 73: return COUNTRY_MALAYSIA;
        case 74: return COUNTRY_MALDIVES;
        case 75: return COUNTRY_MALTA;
        case 76: return COUNTRY_MAURITIUS;
        case 77: return COUNTRY_MEXICO;
        case 78: return COUNTRY_MOLDOVA;
        case 79: return COUNTRY_MONACO;
        case 80: return COUNTRY_MONTENEGRO;
        case 81: return COUNTRY_MOROCCO;
        case 82: return COUNTRY_NAMIBIA;
        case 83: return COUNTRY_NEPAL;
        case 84: return COUNTRY_NETHERLANDS;
        case 85: return COUNTRY_NEW_ZEALAND;
        case 86: return COUNTRY_NICARAGUA;
        case 87: return COUNTRY_NIGERIA;
        case 88: return COUNTRY_NORTH_MACEDONIA;
        case 89: return COUNTRY_NORWAY;
        case 90: return COUNTRY_OMAN;
        case 91: return COUNTRY_PAKISTAN;
        case 92: return COUNTRY_PALESTINE;
        case 93: return COUNTRY_PANAMA;
        case 94: return COUNTRY_PARAGUAY;
        case 95: return COUNTRY_PERU;
        case 96: return COUNTRY_PHILIPPINES;
        case 97: return COUNTRY_POLAND;
        case 98: return COUNTRY_PORTUGAL;
        case 99: return COUNTRY_PUERTO_RICO;
        case 100: return COUNTRY_QATAR;
        case 101: return COUNTRY_ROMANIA;
        case 102: return COUNTRY_RUSSIA;
        case 103: return COUNTRY_SAINT_KITTS_AND_NEVIS;
        case 104: return COUNTRY_SAINT_LUCIA;
        case 105: return COUNTRY_SAUDI_ARABIA;
        case 106: return COUNTRY_SERBIA;
        case 107: return COUNTRY_SINGAPORE;
        case 108: return COUNTRY_SLOVAKIA;
        case 109: return COUNTRY_SLOVENIA;
        case 110: return COUNTRY_SOUTH_AFRICA;
        case 111: return COUNTRY_SOUTH_KOREA;
        case 112: return COUNTRY_SPAIN;
        case 113: return COUNTRY_SRI_LANKA;
        case 114: return COUNTRY_SUDAN;
        case 115: return COUNTRY_SWEDEN;
        case 116: return COUNTRY_SWITZERLAND;
        case 117: return COUNTRY_TAIWAN;
        case 118: return COUNTRY_TANZANIA;
        case 119: return COUNTRY_THAILAND;
        case 120: return COUNTRY_TRINIDAD_AND_TOBAGO;
        case 121: return COUNTRY_TUNISIA;
        case 122: return COUNTRY_TURKEY;
        case 123: return COUNTRY_UAE;
        case 124: return COUNTRY_UK;
        case 125: return COUNTRY_UKRAINE;
        case 126: return COUNTRY_URUGUAY;
        case 127: return COUNTRY_USA;
        case 128: return COUNTRY_UZBEKISTAN;
        case 129: return COUNTRY_VENEZUELA;
        case 130: return COUNTRY_VIETNAM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Country>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Country> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Country>() {
            public Country findValueByNumber(int number) {
              return Country.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ddx.v1.CountriesEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final Country[] VALUES = values();

    public static Country valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Country(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ddx.v1.Country)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/ddx/v1/countries_enum.proto\022\014pro" +
      "to.ddx.v1*\336\026\n\007Country\022\031\n\025COUNTRY_NOT_AVA" +
      "ILABLE\020\000\022\027\n\023COUNTRY_AFGHANISTAN\020\001\022\023\n\017COU" +
      "NTRY_ALBANIA\020\002\022\023\n\017COUNTRY_ALGERIA\020\003\022\037\n\033C" +
      "OUNTRY_ANTIGUA_AND_BARBUDA\020\004\022\025\n\021COUNTRY_" +
      "ARGENTINA\020\005\022\023\n\017COUNTRY_ARMENIA\020\006\022\025\n\021COUN" +
      "TRY_AUSTRALIA\020\007\022\023\n\017COUNTRY_AUSTRIA\020\010\022\026\n\022" +
      "COUNTRY_AZERBAIJAN\020\t\022\023\n\017COUNTRY_BAHAMAS\020" +
      "\n\022\023\n\017COUNTRY_BAHRAIN\020\013\022\026\n\022COUNTRY_BANGLA" +
      "DESH\020\014\022\024\n\020COUNTRY_BARBADOS\020\r\022\023\n\017COUNTRY_" +
      "BELARUS\020\016\022\023\n\017COUNTRY_BELGIUM\020\017\022\023\n\017COUNTR" +
      "Y_BERMUDA\020\020\022\023\n\017COUNTRY_BOLIVIA\020\021\022\"\n\036COUN" +
      "TRY_BOSNIA_AND_HERZEGOVINA\020\022\022\022\n\016COUNTRY_" +
      "BRAZIL\020\023\022\022\n\016COUNTRY_BRUNEI\020\024\022\024\n\020COUNTRY_" +
      "BULGARIA\020\025\022\024\n\020COUNTRY_CAMBODIA\020\026\022\024\n\020COUN" +
      "TRY_CAMEROON\020\027\022\022\n\016COUNTRY_CANADA\020\030\022\032\n\026CO" +
      "UNTRY_CAYMAN_ISLANDS\020\031\022\021\n\rCOUNTRY_CHILE\020" +
      "\032\022\021\n\rCOUNTRY_CHINA\020\033\022\024\n\020COUNTRY_COLOMBIA" +
      "\020\034\022\026\n\022COUNTRY_COSTA_RICA\020\035\022\023\n\017COUNTRY_CR" +
      "OATIA\020\036\022\020\n\014COUNTRY_CUBA\020\037\022\022\n\016COUNTRY_CYP" +
      "RUS\020 \022\023\n\017COUNTRY_CZECHIA\020!\022,\n(COUNTRY_DE" +
      "MOCRATIC_REPUBLIC_OF_THE_CONGO\020\"\022\023\n\017COUN" +
      "TRY_DENMARK\020#\022\036\n\032COUNTRY_DOMINICAN_REPUB" +
      "LIC\020$\022\023\n\017COUNTRY_ECUADOR\020%\022\021\n\rCOUNTRY_EG" +
      "YPT\020&\022\027\n\023COUNTRY_EL_SALVADOR\020\'\022\023\n\017COUNTR" +
      "Y_ESTONIA\020(\022\023\n\017COUNTRY_FINLAND\020)\022\022\n\016COUN" +
      "TRY_FRANCE\020*\022\023\n\017COUNTRY_GEORGIA\020+\022\023\n\017COU" +
      "NTRY_GERMANY\020,\022\021\n\rCOUNTRY_GHANA\020-\022\022\n\016COU" +
      "NTRY_GREECE\020.\022\025\n\021COUNTRY_GUATEMALA\020/\022\021\n\r" +
      "COUNTRY_HAITI\0200\022\024\n\020COUNTRY_HONDURAS\0201\022\025\n" +
      "\021COUNTRY_HONG_KONG\0202\022\023\n\017COUNTRY_HUNGARY\020" +
      "3\022\023\n\017COUNTRY_ICELAND\0204\022\021\n\rCOUNTRY_INDIA\020" +
      "5\022\025\n\021COUNTRY_INDONESIA\0206\022\020\n\014COUNTRY_IRAN" +
      "\0207\022\020\n\014COUNTRY_IRAQ\0208\022\023\n\017COUNTRY_IRELAND\020" +
      "9\022\022\n\016COUNTRY_ISRAEL\020:\022\021\n\rCOUNTRY_ITALY\020;" +
      "\022\027\n\023COUNTRY_IVORY_COAST\020<\022\023\n\017COUNTRY_JAM" +
      "AICA\020=\022\021\n\rCOUNTRY_JAPAN\020>\022\022\n\016COUNTRY_JOR" +
      "DAN\020?\022\026\n\022COUNTRY_KAZAKHSTAN\020@\022\021\n\rCOUNTRY" +
      "_KENYA\020A\022\022\n\016COUNTRY_KOSOVO\020B\022\022\n\016COUNTRY_" +
      "KUWAIT\020C\022\022\n\016COUNTRY_LATVIA\020D\022\021\n\rCOUNTRY_" +
      "LIBYA\020E\022\031\n\025COUNTRY_LIECHTENSTEIN\020F\022\025\n\021CO" +
      "UNTRY_LITHUANIA\020G\022\026\n\022COUNTRY_LUXEMBOURG\020" +
      "H\022\024\n\020COUNTRY_MALAYSIA\020I\022\024\n\020COUNTRY_MALDI" +
      "VES\020J\022\021\n\rCOUNTRY_MALTA\020K\022\025\n\021COUNTRY_MAUR" +
      "ITIUS\020L\022\022\n\016COUNTRY_MEXICO\020M\022\023\n\017COUNTRY_M" +
      "OLDOVA\020N\022\022\n\016COUNTRY_MONACO\020O\022\026\n\022COUNTRY_" +
      "MONTENEGRO\020P\022\023\n\017COUNTRY_MOROCCO\020Q\022\023\n\017COU" +
      "NTRY_NAMIBIA\020R\022\021\n\rCOUNTRY_NEPAL\020S\022\027\n\023COU" +
      "NTRY_NETHERLANDS\020T\022\027\n\023COUNTRY_NEW_ZEALAN" +
      "D\020U\022\025\n\021COUNTRY_NICARAGUA\020V\022\023\n\017COUNTRY_NI" +
      "GERIA\020W\022\033\n\027COUNTRY_NORTH_MACEDONIA\020X\022\022\n\016" +
      "COUNTRY_NORWAY\020Y\022\020\n\014COUNTRY_OMAN\020Z\022\024\n\020CO" +
      "UNTRY_PAKISTAN\020[\022\025\n\021COUNTRY_PALESTINE\020\\\022" +
      "\022\n\016COUNTRY_PANAMA\020]\022\024\n\020COUNTRY_PARAGUAY\020" +
      "^\022\020\n\014COUNTRY_PERU\020_\022\027\n\023COUNTRY_PHILIPPIN" +
      "ES\020`\022\022\n\016COUNTRY_POLAND\020a\022\024\n\020COUNTRY_PORT" +
      "UGAL\020b\022\027\n\023COUNTRY_PUERTO_RICO\020c\022\021\n\rCOUNT" +
      "RY_QATAR\020d\022\023\n\017COUNTRY_ROMANIA\020e\022\022\n\016COUNT" +
      "RY_RUSSIA\020f\022!\n\035COUNTRY_SAINT_KITTS_AND_N" +
      "EVIS\020g\022\027\n\023COUNTRY_SAINT_LUCIA\020h\022\030\n\024COUNT" +
      "RY_SAUDI_ARABIA\020i\022\022\n\016COUNTRY_SERBIA\020j\022\025\n" +
      "\021COUNTRY_SINGAPORE\020k\022\024\n\020COUNTRY_SLOVAKIA" +
      "\020l\022\024\n\020COUNTRY_SLOVENIA\020m\022\030\n\024COUNTRY_SOUT" +
      "H_AFRICA\020n\022\027\n\023COUNTRY_SOUTH_KOREA\020o\022\021\n\rC" +
      "OUNTRY_SPAIN\020p\022\025\n\021COUNTRY_SRI_LANKA\020q\022\021\n" +
      "\rCOUNTRY_SUDAN\020r\022\022\n\016COUNTRY_SWEDEN\020s\022\027\n\023" +
      "COUNTRY_SWITZERLAND\020t\022\022\n\016COUNTRY_TAIWAN\020" +
      "u\022\024\n\020COUNTRY_TANZANIA\020v\022\024\n\020COUNTRY_THAIL" +
      "AND\020w\022\037\n\033COUNTRY_TRINIDAD_AND_TOBAGO\020x\022\023" +
      "\n\017COUNTRY_TUNISIA\020y\022\022\n\016COUNTRY_TURKEY\020z\022" +
      "\017\n\013COUNTRY_UAE\020{\022\016\n\nCOUNTRY_UK\020|\022\023\n\017COUN" +
      "TRY_UKRAINE\020}\022\023\n\017COUNTRY_URUGUAY\020~\022\017\n\013CO" +
      "UNTRY_USA\020\177\022\027\n\022COUNTRY_UZBEKISTAN\020\200\001\022\026\n\021" +
      "COUNTRY_VENEZUELA\020\201\001\022\024\n\017COUNTRY_VIETNAM\020" +
      "\202\001B4Z2github.com/veridil/id-extract-serv" +
      "ice/proto/ddx/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
